# The URL the site will be built for
base_url = "https://simsine.no/dat156"

# The site theme to use.
theme = "linkita"

# The default language.
# "en" is for English.
default_language = "no"

# The site title.
# Will be in all page titles.
title = "DAT156"

# The default author for pages.
# See "extra.profiles".
author = "simsine"

# The site description.
# Used in feeds by default.
description = ""

# Automatically generate a feed.
# Default value: false
generate_feeds = true

# The filenames to use for the feeds.
# e.g. ["rss.xml"]
feed_filenames = ["atom.xml"]

# Build a search index from the pages and section content
# for "default_language".
# build_search_index = true

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# If you disable default favicons, you can use
# the inject support to set your own favicons.
# Default value: false
disable_default_favicon = true

# Reverse the order of prev and next post links.
# Default value: false
invert_page_navigation = true

# Put all your custom variables here
header_menu_name = "header_menu"

[extra.menus]
header_menu = [
  { url = "https://www.frende.no/", name = "Frende Forsikring" },
  { url = "https://github.com/simsine/dat156", name = "Kildekode" },
]

# Replace "your_username" with your username.
[extra.profiles.simsine]

# The URL of avatar.
# e.g. "icons/github.svg"
avatar_url = ""

# A description of what is in the avatar.
avatar_alt = ""

# Invert avatar color in dark mode.
# Default value: false
avatar_invert = false

# Profile name.
# Default value: the username
name = "Simen Strømsnes"

# Profile bio.
# Supports Markdown.
bio = "Dataingeniør student ved HVL Bergen"

# Social icons.
# "name" should be the file name of "static/icons/*.svg" or
# the icon name of https://simpleicons.org/
# "url" supports "$BASE_URL".
# Other variables: "urls", "title", "titles".
social = [
    { name = "home", url = "https://simsine.no" },
    { name = "github", url = "https://github.com/simsine" },
    { name = "email", url = "mailto:example@example.com" },
    { name = "linkedin", url = "https://www.linkedin.com/in/simen-str%C3%B8msnes-572a03268/" },
    { name = "rss", url = "$BASE_URL/atom.xml" },
]
