on: push
name: Build and deploy to GH Pages
jobs:
  build_and_deploy_site:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@master
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          # Provide access token for repo
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
